import { ImageRequireSource } from 'react-native';

/* eslint-disable @typescript-eslint/no-var-requires */
type CountryCodes = {
  [dialCode: string]: Array<string>;
};

interface CountriesListItem {
  name: string;
  iso2: string;
  dialCode: string;
  priority: number;
  areaCodes: ReadonlyArray<string> | null;
}
interface PickerData {
  key: number;
  image: ImageRequireSource;
  label: CountriesListItem['name'];
  dialCode: CountriesListItem['dialCode'];
  iso2: CountriesListItem['iso2'];
}

const countries: Array<{
  name: string;
  iso2: keyof typeof flags;
  dialCode: string;
  priority: number;
  areaCodes: Array<string>;
}> = require('~/resources/files/countries.json');

const flags = {
  ad: require('~/resources/flags/ad.png'),
  ae: require('~/resources/flags/ae.png'),
  af: require('~/resources/flags/af.png'),
  ag: require('~/resources/flags/ag.png'),
  ai: require('~/resources/flags/ai.png'),
  al: require('~/resources/flags/al.png'),
  am: require('~/resources/flags/am.png'),
  ao: require('~/resources/flags/ao.png'),
  ar: require('~/resources/flags/ar.png'),
  as: require('~/resources/flags/as.png'),
  at: require('~/resources/flags/at.png'),
  au: require('~/resources/flags/au.png'),
  aw: require('~/resources/flags/aw.png'),
  ax: require('~/resources/flags/ax.png'),
  az: require('~/resources/flags/az.png'),
  ba: require('~/resources/flags/ba.png'),
  bb: require('~/resources/flags/bb.png'),
  bd: require('~/resources/flags/bd.png'),
  be: require('~/resources/flags/be.png'),
  bf: require('~/resources/flags/bf.png'),
  bg: require('~/resources/flags/bg.png'),
  bh: require('~/resources/flags/bh.png'),
  bi: require('~/resources/flags/bi.png'),
  bj: require('~/resources/flags/bj.png'),
  bl: require('~/resources/flags/bl.png'),
  bm: require('~/resources/flags/bm.png'),
  bn: require('~/resources/flags/bn.png'),
  bo: require('~/resources/flags/bo.png'),
  bq: require('~/resources/flags/bq.png'),
  br: require('~/resources/flags/br.png'),
  bs: require('~/resources/flags/bs.png'),
  bt: require('~/resources/flags/bt.png'),
  bw: require('~/resources/flags/bw.png'),
  by: require('~/resources/flags/by.png'),
  bz: require('~/resources/flags/bz.png'),
  ca: require('~/resources/flags/ca.png'),
  cc: require('~/resources/flags/cc.png'),
  cd: require('~/resources/flags/cd.png'),
  cf: require('~/resources/flags/cf.png'),
  cg: require('~/resources/flags/cg.png'),
  ch: require('~/resources/flags/ch.png'),
  ci: require('~/resources/flags/ci.png'),
  ck: require('~/resources/flags/ck.png'),
  cl: require('~/resources/flags/cl.png'),
  cm: require('~/resources/flags/cm.png'),
  cn: require('~/resources/flags/cn.png'),
  co: require('~/resources/flags/co.png'),
  cr: require('~/resources/flags/cr.png'),
  cu: require('~/resources/flags/cu.png'),
  cv: require('~/resources/flags/cv.png'),
  cw: require('~/resources/flags/cw.png'),
  cx: require('~/resources/flags/cx.png'),
  cy: require('~/resources/flags/cy.png'),
  cz: require('~/resources/flags/cz.png'),
  de: require('~/resources/flags/de.png'),
  dj: require('~/resources/flags/dj.png'),
  dk: require('~/resources/flags/dk.png'),
  dm: require('~/resources/flags/dm.png'),
  do: require('~/resources/flags/do.png'),
  dz: require('~/resources/flags/dz.png'),
  ec: require('~/resources/flags/ec.png'),
  ee: require('~/resources/flags/ee.png'),
  eg: require('~/resources/flags/eg.png'),
  eh: require('~/resources/flags/eh.png'),
  er: require('~/resources/flags/er.png'),
  es: require('~/resources/flags/es.png'),
  et: require('~/resources/flags/et.png'),
  fi: require('~/resources/flags/fi.png'),
  fj: require('~/resources/flags/fj.png'),
  fk: require('~/resources/flags/fk.png'),
  fm: require('~/resources/flags/fm.png'),
  fo: require('~/resources/flags/fo.png'),
  fr: require('~/resources/flags/fr.png'),
  ga: require('~/resources/flags/ga.png'),
  gb: require('~/resources/flags/gb.png'),
  gd: require('~/resources/flags/gd.png'),
  ge: require('~/resources/flags/ge.png'),
  gf: require('~/resources/flags/gf.png'),
  gg: require('~/resources/flags/gg.png'),
  gh: require('~/resources/flags/gh.png'),
  gi: require('~/resources/flags/gi.png'),
  gm: require('~/resources/flags/gm.png'),
  gn: require('~/resources/flags/gn.png'),
  gp: require('~/resources/flags/gp.png'),
  gq: require('~/resources/flags/gq.png'),
  gr: require('~/resources/flags/gr.png'),
  gt: require('~/resources/flags/gt.png'),
  gu: require('~/resources/flags/gu.png'),
  gw: require('~/resources/flags/gw.png'),
  gy: require('~/resources/flags/gy.png'),
  hk: require('~/resources/flags/hk.png'),
  hn: require('~/resources/flags/hn.png'),
  hr: require('~/resources/flags/hr.png'),
  ht: require('~/resources/flags/ht.png'),
  hu: require('~/resources/flags/hu.png'),
  id: require('~/resources/flags/id.png'),
  ie: require('~/resources/flags/ie.png'),
  il: require('~/resources/flags/il.png'),
  im: require('~/resources/flags/im.png'),
  in: require('~/resources/flags/in.png'),
  io: require('~/resources/flags/io.png'),
  iq: require('~/resources/flags/iq.png'),
  ir: require('~/resources/flags/ir.png'),
  is: require('~/resources/flags/is.png'),
  it: require('~/resources/flags/it.png'),
  je: require('~/resources/flags/je.png'),
  jm: require('~/resources/flags/jm.png'),
  jo: require('~/resources/flags/jo.png'),
  jp: require('~/resources/flags/jp.png'),
  ke: require('~/resources/flags/ke.png'),
  kg: require('~/resources/flags/kg.png'),
  kh: require('~/resources/flags/kh.png'),
  ki: require('~/resources/flags/ki.png'),
  km: require('~/resources/flags/km.png'),
  kn: require('~/resources/flags/kn.png'),
  kp: require('~/resources/flags/kp.png'),
  kr: require('~/resources/flags/kr.png'),
  ks: require('~/resources/flags/ks.png'),
  kw: require('~/resources/flags/kw.png'),
  ky: require('~/resources/flags/ky.png'),
  kz: require('~/resources/flags/kz.png'),
  la: require('~/resources/flags/la.png'),
  lb: require('~/resources/flags/lb.png'),
  lc: require('~/resources/flags/lc.png'),
  li: require('~/resources/flags/li.png'),
  lk: require('~/resources/flags/lk.png'),
  lr: require('~/resources/flags/lr.png'),
  ls: require('~/resources/flags/ls.png'),
  lt: require('~/resources/flags/lt.png'),
  lu: require('~/resources/flags/lu.png'),
  lv: require('~/resources/flags/lv.png'),
  ly: require('~/resources/flags/ly.png'),
  ma: require('~/resources/flags/ma.png'),
  mc: require('~/resources/flags/mc.png'),
  md: require('~/resources/flags/md.png'),
  me: require('~/resources/flags/me.png'),
  mf: require('~/resources/flags/mf.png'),
  mg: require('~/resources/flags/mg.png'),
  mh: require('~/resources/flags/mh.png'),
  mk: require('~/resources/flags/mk.png'),
  ml: require('~/resources/flags/ml.png'),
  mm: require('~/resources/flags/mm.png'),
  mn: require('~/resources/flags/mn.png'),
  mo: require('~/resources/flags/mo.png'),
  mp: require('~/resources/flags/mp.png'),
  mq: require('~/resources/flags/mq.png'),
  mr: require('~/resources/flags/mr.png'),
  ms: require('~/resources/flags/ms.png'),
  mt: require('~/resources/flags/mt.png'),
  mu: require('~/resources/flags/mu.png'),
  mv: require('~/resources/flags/mv.png'),
  mw: require('~/resources/flags/mw.png'),
  mx: require('~/resources/flags/mx.png'),
  my: require('~/resources/flags/my.png'),
  mz: require('~/resources/flags/mz.png'),
  na: require('~/resources/flags/na.png'),
  nc: require('~/resources/flags/nc.png'),
  ne: require('~/resources/flags/ne.png'),
  nf: require('~/resources/flags/nf.png'),
  ng: require('~/resources/flags/ng.png'),
  ni: require('~/resources/flags/ni.png'),
  nl: require('~/resources/flags/nl.png'),
  no: require('~/resources/flags/no.png'),
  np: require('~/resources/flags/np.png'),
  nr: require('~/resources/flags/nr.png'),
  nu: require('~/resources/flags/nu.png'),
  nz: require('~/resources/flags/nz.png'),
  om: require('~/resources/flags/om.png'),
  pa: require('~/resources/flags/pa.png'),
  pe: require('~/resources/flags/pe.png'),
  pf: require('~/resources/flags/pf.png'),
  pg: require('~/resources/flags/pg.png'),
  ph: require('~/resources/flags/ph.png'),
  pk: require('~/resources/flags/pk.png'),
  pl: require('~/resources/flags/pl.png'),
  pm: require('~/resources/flags/pm.png'),
  pr: require('~/resources/flags/pr.png'),
  ps: require('~/resources/flags/ps.png'),
  pt: require('~/resources/flags/pt.png'),
  pw: require('~/resources/flags/pw.png'),
  py: require('~/resources/flags/py.png'),
  qa: require('~/resources/flags/qa.png'),
  re: require('~/resources/flags/re.png'),
  ro: require('~/resources/flags/ro.png'),
  rs: require('~/resources/flags/rs.png'),
  ru: require('~/resources/flags/ru.png'),
  rw: require('~/resources/flags/rw.png'),
  sa: require('~/resources/flags/sa.png'),
  sb: require('~/resources/flags/sb.png'),
  sc: require('~/resources/flags/sc.png'),
  sd: require('~/resources/flags/sd.png'),
  se: require('~/resources/flags/se.png'),
  sg: require('~/resources/flags/sg.png'),
  sh: require('~/resources/flags/sh.png'),
  si: require('~/resources/flags/si.png'),
  sj: require('~/resources/flags/sj.png'),
  sk: require('~/resources/flags/sk.png'),
  sl: require('~/resources/flags/sl.png'),
  sm: require('~/resources/flags/sm.png'),
  sn: require('~/resources/flags/sn.png'),
  so: require('~/resources/flags/so.png'),
  sr: require('~/resources/flags/sr.png'),
  ss: require('~/resources/flags/ss.png'),
  st: require('~/resources/flags/st.png'),
  sv: require('~/resources/flags/sv.png'),
  sx: require('~/resources/flags/sx.png'),
  sy: require('~/resources/flags/sy.png'),
  sz: require('~/resources/flags/sz.png'),
  tc: require('~/resources/flags/tc.png'),
  td: require('~/resources/flags/td.png'),
  tg: require('~/resources/flags/tg.png'),
  th: require('~/resources/flags/th.png'),
  tj: require('~/resources/flags/tj.png'),
  tk: require('~/resources/flags/tk.png'),
  tl: require('~/resources/flags/tl.png'),
  tm: require('~/resources/flags/tm.png'),
  tn: require('~/resources/flags/tn.png'),
  to: require('~/resources/flags/to.png'),
  tr: require('~/resources/flags/tr.png'),
  tt: require('~/resources/flags/tt.png'),
  tv: require('~/resources/flags/tv.png'),
  tw: require('~/resources/flags/tw.png'),
  tz: require('~/resources/flags/tz.png'),
  ua: require('~/resources/flags/ua.png'),
  ug: require('~/resources/flags/ug.png'),
  us: require('~/resources/flags/us.png'),
  uy: require('~/resources/flags/uy.png'),
  uz: require('~/resources/flags/uz.png'),
  va: require('~/resources/flags/va.png'),
  vc: require('~/resources/flags/vc.png'),
  ve: require('~/resources/flags/ve.png'),
  vg: require('~/resources/flags/vg.png'),
  vi: require('~/resources/flags/vi.png'),
  vn: require('~/resources/flags/vn.png'),
  vu: require('~/resources/flags/vu.png'),
  wf: require('~/resources/flags/wf.png'),
  ws: require('~/resources/flags/ws.png'),
  ye: require('~/resources/flags/ye.png'),
  yt: require('~/resources/flags/yt.png'),
  za: require('~/resources/flags/za.png'),
  zm: require('~/resources/flags/zm.png'),
  zw: require('~/resources/flags/zw.png'),
};

const addCountryCode = (
  countryCodes: CountryCodes,
  iso2: string,
  dialCode: string,
  priority?: number,
) => {
  if (!(dialCode in countryCodes)) {
    countryCodes[dialCode] = [];
  }

  const index = priority || 0;
  countryCodes[dialCode][index] = iso2;
  return countryCodes;
};

export const countryCodes = countries.reduce((obj, country) => {
  let nextObj = addCountryCode(
    obj,
    country.iso2,
    country.dialCode,
    country.priority,
  );

  if (country.areaCodes) {
    country.areaCodes.forEach((areaCode) => {
      nextObj = addCountryCode(
        nextObj,
        country.iso2,
        country.dialCode + areaCode,
      );
    });
  }

  return nextObj;
}, {} as CountryCodes);

export default countries.map<PickerData>((country, index) => ({
  key: index,
  image: flags[country.iso2],
  label: country.name,
  dialCode: `+${country.dialCode}`,
  iso2: country.iso2,
}));
